### ISSUE TITLE
[Bug]: Director Daemon does not start: DB configuration is not valid

### ISSUE THREAD

**Issue by jasase** [Icinga/helm-charts#12]
### Affected Chart

icinga-stack

### Which version of the app contains the bug?

0.1.0

### Please describe your problem

Creating clean installation of helm chart `icinga-stack` with this config values:

```
icingaweb2:
  auth:
    admin_password: SecurePassword1!
global:
  api:
    users:
      director:
        password: SecurePassword1!
      icingaweb:
        password: SecurePassword1!
  databases:
    director:
      password: SecurePassword1!
    icingadb:
      password: SecurePassword1!
    icingaweb2:
      password: SecurePassword1!
    x509:
      password: SecurePassword1!
icinga2:
  config:
    ticket_salt: 17243691872387e9yesrv213875654vc98761256v9876
```

Everything is running except the Director daemon which fails with this message:
`DB configuration is not valid`
