### ISSUE TITLE
[Bug]:  securitycontext values not being respected

### ISSUE THREAD

**Issue by td-raystevens** [Icinga/helm-charts#55]
### Affected Chart

icinga-stack

### Which version of the app contains the bug?

0.3.0

### Please describe your problem

We have the need to set add: NET_RAW to capabilities under security context within the containers of the icinga2 pod

We've tried this within the values file using both

```
icinga2:
  securityContext:
    capabilities:
      add:
        - NET_RAW
```

and

```
icinga2:
  podSecurityContext:
    capabilities:
      add:
        - NET_RAW
```
However, these change within the values file are not reflected in the statefulset nor the pod's end result.
