### ISSUE TITLE
[Bug]: Wrong configuration in /etc/icingaweb2/config.ini inside the container

### ISSUE THREAD

**Issue by Donien** [Icinga/helm-charts#6]
### Affected Chart

icingaweb2

### Which version of the app contains the bug?

0.1.0

### Please describe your problem

When using this helm chart and not providing any additional parameters (apart from required ones) the resulting **/etc/icingaweb2/config.ini** inside the according container looks as follows:  

```ini
[global]
config_resource = db
config_backend  = icingaweb2db
```

Icinga Web 2 then tries to load a config resource of the name `db` which does not exist.  

![Screenshot 2023-05-31 at 15-25-24 Current Incidents Dashboard Icinga Web](https://github.com/Icinga/helm-charts/assets/88634789/f3c8742e-78e0-418d-b207-47d954daf8a2)

Manually selecting the config resource and saving in the web interface fixes that problem.  

## Proposed solution

Inside `charts/icinga-stack/charts/icingaweb2/templates/_icingaweb-config.tpl` we could change

```yaml
- name: icingaweb.config.global.config_backend
  value: {{ .Values.auth.resource | default .Values.global.databases.icingaweb2.database | quote }}
- name: icingaweb.config.global.config_resource
  value: {{ .Values.auth.type | quote }}
```

to

```yaml
- name: icingaweb.config.global.config_resource
  value: {{ .Values.auth.resource | default .Values.global.databases.icingaweb2.database | quote }}
```

thus creating the correct format according to the [documentation](https://icinga.com/docs/icinga-web/latest/doc/03-Configuration/#configuration-general).

New **/etc/icingaweb2/config.ini**:  

```ini
[global]
config_resource = icingaweb2db
```
