### ISSUE TITLE
[Bug]: influxdb setting forces optional variables to be set

### ISSUE THREAD

**Issue by borgstorm** [Icinga/helm-charts#60]
### Affected Chart

icinga2

### Which version of the app contains the bug?

0.3.0

### Please describe your problem

When attempting to enable an https connection to an influxdb the chart fails due to un-set variables.

#### Helm values:
```
    influxdb:
      enabled: true
      host: influx
      port: 443
      database: icinga2
      ssl_enable: true
     [...]
```
#### error message: 

> influxdb secret not set. Set .Values.features.influxdb.tlsSecret

Assigning a value to `tlsSecret` in turn returns similar errors saying that the following are not set:

> .Values.features.influxdb.caSecretKey
> .Values.features.influxdb.keySecretKey
> .Values.features.influxdb.certSecretKey

These attribute are all optional according to [the documentation](https://icinga.com/docs/icinga-2/latest/doc/09-object-types/#objecttype-influxdbwriter). I have also tested it on a VM install on RHEL and the influx writer works as expected, with `ssl_enable: true` and without any of the extra attributes.
